apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: microserviciocxas-policy
  namespace: cesar
specs:
  podSelector:
    matchLabels:
      app: microserviciocxas
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
