apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: microserviciocxas-policy
  namespace: cesar
spec:
  podSelector:
    matchLabels:
      app: microserviciocxas
  policyTypes:
    - Ingress
    - Egress
